### ISSUE TITLE
Make unit cell expansion optional in base workchain

### ISSUE THREAD

**Issue by kjappelbaum** [yakutovicha/aiida-raspa#14]
As this is, if done correctly, a non-trivial transformation we would like to give the use the option to disable this feature (which is also useful for debugging purposes).

**Comment by yakutovicha** [comment]
The function is not used in the plugin anymore, so I will close the issue once the [multiply_unitcell.py](https://github.com/yakutovicha/aiida-raspa/blob/develop/aiida_raspa/utils/multiply_unitcell.py) file is removed
