### ISSUE TITLE
Missing MANIFEST.in

### ISSUE THREAD

**Issue by giovannipizzi** [yakutovicha/aiida-raspa#2]
One needs to add the `setup.json` file to the MANIFEST.in (see examples in other plugins) so that the file is present in packages on, e.g., pypi.
Also, check e.g. the zeopp plugin to include properly a README.md in setup.py.

I didn't check if you have other plugins with similar issues.

**Comment by yakutovicha** [comment]
Sure, I will take care of that.

Thanks!

**Comment by yakutovicha** [comment]
fixed with e4b16b80d45e138ff00dd65c4559eb41835ddfb7
