### ISSUE TITLE
Keep consistency: unit/units

### ISSUE THREAD

**Issue by danieleongari** [yakutovicha/aiida-raspa#26]
Hi,
please change the output API to keep consistency in the `{quantity}_unit(s)` in the labels of the Dict. 

According to https://en.wikipedia.org/wiki/Unit_of_measurement, 
the common term is `unit` (i.e., singular). 
For example, even when the unit is composed by different units, it keeps the singular 
> [...] in terms of the unit microlitres per metre [...]

**Comment by yakutovicha** [comment]
thanks, will do
