### ISSUE TITLE
"Average Widom Rosenbluth-weight" not parsed

### ISSUE THREAD

**Issue by kdeeg** [yakutovicha/aiida-raspa#3]
When Widom insertions are performed, one of the quantities in the RASPA output is "Average Widom Rosenbluth-weight" for the specified component. However, this quantity is not parsed by the raspa plugin (i.e. it does not appear as one of the outputs in either ParameterData object output_parameters or component_0). Attached is an example RASPA input and output file that suffers this problem.

[output_framework_1.1.1_298.000000_0.data.txt](https://github.com/yakutovicha/aiida-raspa/files/2590397/output_framework_1.1.1_298.000000_0.data.txt)
[simulation.input.txt](https://github.com/yakutovicha/aiida-raspa/files/2590398/simulation.input.txt)

**Comment by yakutovicha** [comment]
I tried to run the same simulation, but in my case the "Average Widom Rosenbluth-weight" was actually parsed.

In that particular case the name of the output parameter is chosen to be the same as the name of the section.
```
Average Widom Rosenbluth factor:
================================
        Block[ 0] 28.5507 [-]
        Block[ 1] 28.0786 [-]
        Block[ 2] 28.5465 [-]
        Block[ 3] 27.6811 [-]
        Block[ 4] 28.2071 [-]
        ------------------------------------------------------------------------------
        [CO2] Average Widom Rosenbluth-weight:   28.2128 +/- 0.648872 [-]
```
So in that particular case the outputs are stored under "widom_rosenbluth_factor_..." keys:
```
$ verdi data parameter show  7223
{
...
  "widom_rosenbluth_factor_average": 28.2128, 
  "widom_rosenbluth_factor_dev": 0.648872, 
  "widom_rosenbluth_factor_units": "-"
}
```
@kdeeg please have a look in the component_0 output dictionary and check if those keys are present and the values are correct.

**Comment by yakutovicha** [comment]
@kdeeg, I will close the issue. Reopen it if you think it is not resolved. Thanks!
